### PR TITLE
Post 0.9.0 fixes

### LINKED ISSUE #81: hicup2homer is not executable in v0.9.0
Hi,
It seems that during the release process, the hicup2homer lost the executable mode:
```
[ldelisle@SV-49-002 HiCUP]$ git checkout v0.9.0
HEAD is now at ce79a28 Merge branch 'documentation'
[ldelisle@SV-49-002 HiCUP]$ ls -alh Conversion/
total 84K
drwxr-xr-x  2 ldelisle ldelisle 4.0K Feb 14 20:28 .
drwxr-xr-x 12 ldelisle ldelisle 4.0K Feb 14 20:28 ..
-rwxr-xr-x  1 ldelisle ldelisle  11K Feb 14 20:28 hicup2fithic
-rwxr-xr-x  1 ldelisle ldelisle 4.5K Feb 14 20:28 hicup2gothic
-rwxr-xr-x  1 ldelisle ldelisle 5.5K Feb 14 20:28 hicup2hicpipe
-rw-r--r--  1 ldelisle ldelisle 5.2K Feb 14 20:28 hicup2homer
-rwxr-xr-x  1 ldelisle ldelisle  20K Feb 14 20:28 hicup2juicer
-rwxr-xr-x  1 ldelisle ldelisle  17K Feb 14 20:28 hicup2ncc
[ldelisle@SV-49-002 HiCUP]$ git checkout v0.8.3 
Previous HEAD position was ce79a28 Merge branch 'documentation'
HEAD is now at 94c7a73 Additional release notes update
[ldelisle@SV-49-002 HiCUP]$ ls -alh Conversion/
total 56K
drwxr-xr-x  2 ldelisle ldelisle 4.0K Feb 14 20:29 .
drwxr-xr-x 11 ldelisle ldelisle 4.0K Feb 14 20:29 ..
-rwxr-xr-x  1 ldelisle ldelisle  11K Feb 14 20:29 hicup2fithic
-rwxr-xr-x  1 ldelisle ldelisle 4.4K Feb 14 20:29 hicup2gothic
-rwxr-xr-x  1 ldelisle ldelisle 5.4K Feb 14 20:29 hicup2hicpipe
-rwxr-xr-x  1 ldelisle ldelisle 5.6K Feb 14 20:29 hicup2homer
-rwxr-xr-x  1 ldelisle ldelisle 9.0K Feb 14 20:29 hicup2juicer

```

### PR DESCRIPTION
**Pull request by lldelisle**
Fixes #81 #82

### CODE REVIEW

**Comment by StevenWingett** [comment]
Thanks for the comments etc. on the latest release.   I'll take a look tomorrow when I'm back in the office.

**Comment by StevenWingett** [comment]
Thanks for spotting these issues with the latest release.

**Comment by lldelisle** [comment]
What do you prefer for conda:
- I merge https://github.com/bioconda/bioconda-recipes/pull/39376 where I incorporated these 2 fixes before making the recipe.
- I do not put the 0.9.0 in conda and wait for a new release.

**Comment by StevenWingett** [comment]
Hi,

I can release 0.9.1 today.  Could this release go into Conda?  I'll also create a HiCUP development branch so all updates can be made to here (I forgot to do this after the last release).  Could we update Conda after using the 0.9.1 release?

Also, thanks for helping out with the unit testing (Github Actions).  I've been thinking for some time that this need re-doing.  Using a human genome Hi-C test dataset is ideal so users can check they can get HiCUP working.  But for unit testing I think a human genome is simply too large.  The FASTA files take a while to download and building a Bowtie2 index takes a long time.  In fact this GitHub Actions recipe can time out before it is complete.

I think it would be preferable to use a much smaller genome (e.g. yeast) for the GitHub Actions test (but keep the human test dataset for people wanting to try out the software).  This would make the unit testing much more efficient.  What do you think?

Thanks very much for your help :-)

Steven

**Comment by lldelisle** [comment]
For the release: You need to make a release on github and then I can create a conda package.

For the CI, what I did for the galaxy wrapper of hicup is to map only on chromosome 21 and 22. You can see it here:
https://github.com/bgruening/galaxytools/tree/master/tools/hicup/test-data

And this goes quite fast and fit into a github so I can do it if you want.

**Pull request merged**
