### PR TITLE
add new option to hicup2juicer + keep read name

### PR DESCRIPTION
**Pull request by lldelisle**
Note: This PR has more commits as development is behind master.

This PR proposes 2 changes:
- First keep the read name instead of an index
- Then, propose an option to write to OUT without storing and sorting. This is super useful when working with large experiments.

### CODE REVIEW

**Comment by StevenWingett** [comment]
Hi,

Thanks for this.  TO keep these files small could we:

**Comment by StevenWingett** [comment]
Hi,

Thanks for that!

To keep output files small could we: 

1) keep the read name instead of an index - make this an option, but the default is to use the index number

Also, please could we remove those 2 new datafiles that have been added to the repo.

Thanks,
Steven

**Comment by lldelisle** [comment]
Sure I can implement it.
For the 2 files I added, one is already in the master branch. The second one I added it because I use it in the CI...

**Comment by lldelisle** [comment]
Maybe you can merge master in development so you better see my changes.

**Pull request merged**
